import 'package:uuid/uuid.dart';
import '../models/exam.dart';
import '../models/study_session.dart';
import '../models/user_profile.dart';
import '../models/fixed_block.dart';

class StudySessionGenerator {
  static const _uuid = Uuid();

  static List<StudySession> generateStudySessions({
    required Exam exam,
    required double? latestGrade,
    required UserProfile userProfile,
    required List<FixedBlock> fixedBlocks,
    required List<StudySession> existingStudySessions,
  }) {
    final now = DateTime.now();
    final today = DateTime(now.year, now.month, now.day);
    final examDate = DateTime(exam.examDate.year, exam.examDate.month, exam.examDate.day);
    
    final daysUntilExam = examDate.difference(today).inDays;
    
    if (daysUntilExam <= 0) {
      return [];
    }

    final gradeFactor = (10 - (latestGrade ?? 5.0)) / 10;
    
    final proximityFactor = daysUntilExam <= 1 
        ? 1.0 
        : (1 / daysUntilExam).clamp(0.0, 1.0);
    
    final priorityScore = (gradeFactor * 0.6) + (proximityFactor * 0.4);
    
    var totalHours = priorityScore * daysUntilExam * 1.5;
    totalHours = totalHours.clamp(1.0, daysUntilExam * userProfile.maxStudyHoursPerDay.toDouble());
    
    final maxSessionHours = 3.0;
    final minSessionMinutes = 30;
    
    final availableDays = <DateTime>[];
    for (int i = 0; i < daysUntilExam; i++) {
      final day = today.add(Duration(days: i));
      final dayName = _getDayName(day.weekday);
      if (userProfile.preferredStudyDays.contains(dayName.toLowerCase())) {
        availableDays.add(day);
      }
    }
    
    if (availableDays.isEmpty) {
      return [];
    }
    
    final userStartParts = userProfile.preferredStudyStartTime.split(':');
    final userEndParts = userProfile.preferredStudyEndTime.split(':');
    final userStartMinutes = int.parse(userStartParts[0]) * 60 + int.parse(userStartParts[1]);
    final userEndMinutes = int.parse(userEndParts[0]) * 60 + int.parse(userEndParts[1]);
    
    final generatedSessions = <StudySession>[];
    var remainingHours = totalHours;
    var dayIndex = 0;
    
    while (remainingHours > 0 && dayIndex < availableDays.length) {
      final day = availableDays[dayIndex];
      final dayName = _getDayName(day.weekday);
      
      final dayFixedBlocks = fixedBlocks
          .where((b) => b.dayOfWeek.toLowerCase() == dayName.toLowerCase())
          .toList();
      
      final dayExistingSessions = existingStudySessions
          .where((s) => _isSameDay(s.date, day))
          .toList();
      
      final availableSlots = _findAvailableSlots(
        day,
        dayFixedBlocks,
        dayExistingSessions,
        userStartMinutes,
        userEndMinutes,
        minSessionMinutes,
      );
      
      for (final slot in availableSlots) {
        if (remainingHours <= 0) break;
        
        final slotDuration = (slot['end']! - slot['start']!) ~/ 60;
        if (slotDuration < minSessionMinutes ~/ 60) continue;
        
        final sessionDuration = slotDuration.clamp(minSessionMinutes, maxSessionHours * 60).toInt();
        final hoursToSchedule = remainingHours.clamp(0, sessionDuration / 60);
        
        if (hoursToSchedule < minSessionMinutes / 60) continue;
        
        final startTime = _minutesToTime(slot['start']!);
        final endMinutes = slot['start']! + sessionDuration;
        final endTime = _minutesToTime(endMinutes.clamp(slot['start']!, slot['end']!));
        
        final session = StudySession(
          id: _uuid.v4(),
          userId: exam.userId,
          examId: exam.id,
          subjectId: exam.subjectId,
          date: day,
          startTime: startTime,
          endTime: endTime,
          durationMinutes: sessionDuration,
          completed: false,
          autoGenerated: true,
        );
        
        generatedSessions.add(session);
        remainingHours -= sessionDuration / 60;
      }
      
      dayIndex++;
    }
    
    return generatedSessions;
  }

  static List<Map<String, int>> _findAvailableSlots(
    DateTime day,
    List<FixedBlock> fixedBlocks,
    List<StudySession> existingSessions,
    int userStartMinutes,
    int userEndMinutes,
    int minSessionMinutes,
  ) {
    final occupied = <_TimeSlot>[];
    
    for (final block in fixedBlocks) {
      final startParts = block.startTime.split(':');
      final endParts = block.endTime.split(':');
      occupied.add(_TimeSlot(
        start: int.parse(startParts[0]) * 60 + int.parse(startParts[1]),
        end: int.parse(endParts[0]) * 60 + int.parse(endParts[1]),
      ));
    }
    
    for (final session in existingSessions) {
      final startParts = session.startTime.split(':');
      final endParts = session.endTime.split(':');
      occupied.add(_TimeSlot(
        start: int.parse(startParts[0]) * 60 + int.parse(startParts[1]),
        end: int.parse(endParts[0]) * 60 + int.parse(endParts[1]),
      ));
    }
    
    occupied.sort((a, b) => a.start.compareTo(b.start));
    
    final availableSlots = <Map<String, int>>[];
    var currentStart = userStartMinutes;
    
    for (final slot in occupied) {
      if (slot.start - currentStart >= minSessionMinutes) {
        availableSlots.add({
          'start': currentStart,
          'end': slot.start,
        });
      }
      currentStart = slot.end;
    }
    
    if (userEndMinutes - currentStart >= minSessionMinutes) {
      availableSlots.add({
        'start': currentStart,
        'end': userEndMinutes,
      });
    }
    
    return availableSlots;
  }

  static String _getDayName(int weekday) {
    const days = ['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'];
    return days[weekday - 1];
  }

  static bool _isSameDay(DateTime a, DateTime b) {
    return a.year == b.year && a.month == b.month && a.day == b.day;
  }

  static String _minutesToTime(int minutes) {
    final hours = minutes ~/ 60;
    final mins = minutes % 60;
    return '${hours.toString().padLeft(2, '0')}:${mins.toString().padLeft(2, '0')}';
  }
}

class _TimeSlot {
  final int start;
  final int end;
  
  _TimeSlot({required this.start, required this.end});
}