import 'package:supabase_flutter/supabase_flutter.dart';
import '../models/study_session.dart';

class StudySessionRepository {
  final SupabaseClient _client = Supabase.instance.client;

  Future<List<StudySession>> getStudySessions(String userId) async {
    final response = await _client
        .from('study_sessions')
        .select()
        .eq('user_id', userId)
        .order('date', ascending: true)
        .order('start_time', ascending: true);
    return response.map((e) => StudySession.fromMap(e)).toList();
  }

  Future<List<StudySession>> getStudySessionsByDate(String userId, DateTime date) async {
    final dateStr = date.toIso8601String().split('T')[0];
    final response = await _client
        .from('study_sessions')
        .select()
        .eq('user_id', userId)
        .eq('date', dateStr)
        .order('start_time', ascending: true);
    return response.map((e) => StudySession.fromMap(e)).toList();
  }

  Future<List<StudySession>> getStudySessionsByExam(String userId, String examId) async {
    final response = await _client
        .from('study_sessions')
        .select()
        .eq('user_id', userId)
        .eq('exam_id', examId)
        .order('date', ascending: true);
    return response.map((e) => StudySession.fromMap(e)).toList();
  }

  Future<List<StudySession>> getFutureStudySessions(String userId) async {
    final now = DateTime.now();
    final today = DateTime(now.year, now.month, now.day);
    final response = await _client
        .from('study_sessions')
        .select()
        .eq('user_id', userId)
        .gte('date', today.toIso8601String().split('T')[0])
        .eq('completed', false)
        .order('date', ascending: true);
    return response.map((e) => StudySession.fromMap(e)).toList();
  }

  Future<StudySession> createStudySession(StudySession session) async {
    final response = await _client.from('study_sessions').insert(session.toMap()).select().single();
    return StudySession.fromMap(response);
  }

  Future<void> createStudySessions(List<StudySession> sessions) async {
    await _client.from('study_sessions').insert(sessions.map((e) => e.toMap()).toList());
  }

  Future<void> toggleSessionComplete(String sessionId, bool completed) async {
    await _client.from('study_sessions').update({'completed': completed}).eq('id', sessionId);
  }

  Future<void> deleteStudySession(String sessionId) async {
    await _client.from('study_sessions').delete().eq('id', sessionId);
  }

  Future<void> deleteStudySessionsByExam(String examId) async {
    await _client.from('study_sessions').delete().eq('exam_id', examId);
  }

  Future<void> deleteFutureAutoGeneratedSessions(String userId, String subjectId) async {
    final now = DateTime.now();
    final today = DateTime(now.year, now.month, now.day);
    await _client.from('study_sessions').delete().eq('user_id', userId).eq('subject_id', subjectId).eq('auto_generated', true).gte('date', today.toIso8601String().split('T')[0]);
  }

  Future<int> getSessionCountByExam(String userId, String examId) async {
    final response = await _client
        .from('study_sessions')
        .select('id')
        .eq('user_id', userId)
        .eq('exam_id', examId);
    return response.length;
  }
}