class StudySession {
  final String id;
  final String userId;
  final String? examId;
  final String subjectId;
  final DateTime date;
  final String startTime;
  final String endTime;
  final int durationMinutes;
  final bool completed;
  final bool autoGenerated;

  StudySession({
    required this.id,
    required this.userId,
    this.examId,
    required this.subjectId,
    required this.date,
    required this.startTime,
    required this.endTime,
    required this.durationMinutes,
    required this.completed,
    required this.autoGenerated,
  });

  factory StudySession.fromMap(Map<String, dynamic> map) {
    return StudySession(
      id: map['id'] as String,
      userId: map['user_id'] as String,
      examId: map['exam_id'] as String?,
      subjectId: map['subject_id'] as String,
      date: DateTime.parse(map['date'] as String),
      startTime: map['start_time'] as String,
      endTime: map['end_time'] as String,
      durationMinutes: map['duration_minutes'] as int,
      completed: map['completed'] as bool? ?? false,
      autoGenerated: map['auto_generated'] as bool? ?? true,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'user_id': userId,
      'exam_id': examId,
      'subject_id': subjectId,
      'date': date.toIso8601String().split('T')[0],
      'start_time': startTime,
      'end_time': endTime,
      'duration_minutes': durationMinutes,
      'completed': completed,
      'auto_generated': autoGenerated,
    };
  }

  StudySession copyWith({
    String? id,
    String? userId,
    String? examId,
    String? subjectId,
    DateTime? date,
    String? startTime,
    String? endTime,
    int? durationMinutes,
    bool? completed,
    bool? autoGenerated,
  }) {
    return StudySession(
      id: id ?? this.id,
      userId: userId ?? this.userId,
      examId: examId ?? this.examId,
      subjectId: subjectId ?? this.subjectId,
      date: date ?? this.date,
      startTime: startTime ?? this.startTime,
      endTime: endTime ?? this.endTime,
      durationMinutes: durationMinutes ?? this.durationMinutes,
      completed: completed ?? this.completed,
      autoGenerated: autoGenerated ?? this.autoGenerated,
    );
  }
}